name: Build and Push Docker Image with Gradle

on:
  push:
    branches:
      - main
      - develop 
      - master # Add other branches if needed
  workflow_dispatch:

jobs:
  build:
    runs-on: actions-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t dhananjay01/my-springboot-app:${{ github.sha }} .
          docker push dhananjay01/my-springboot-app:${{ github.sha }}
