name: Create GitHub Issue

on:
  workflow_dispatch: 
    inputs:
       title:
        description: "Issue title"
        required: true
        type: string 
jobs:
  create_issue:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { owner, repo } = context.repo;
            const title = "${{ github.event.inputs.title }}";
            const body = "This is an automatically created issue. Please review it!";
            
            const issues = await github.rest.issues.listForRepo({ owner, repo, state: "open" });
            const issueExists = issues.data.some(issue => issue.title === title);

            if (!issueExists) {
              github.rest.issues.create({
                owner,
                repo,
                title: title,
                body: body,
                labels: ["automated", "bot"]
              });
              console.log("✅ Issue created successfully!");
            } else {
              console.log("⚠️ Issue already exists, skipping creation.");
            }
