name: Comment on Issue

on:
  issues:
    types: [opened] # Runs when a new issue is opened
  workflow_dispatch: # Allows manual execution

jobs:
  comment:
    runs-on: self-hosted
    
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "👋 Thanks for opening this issue! We’ll take a look soon. 🚀"
            });
